In [93]:
import pandas as pd
from efficient_apriori import apriori

In [94]:
df = pd.read_csv('Online Retail.csv').sample(1000)

In [95]:
df.isna().sum()

InvoiceNo        0
StockCode        0
Description      2
Quantity         0
InvoiceDate      0
UnitPrice        0
CustomerID     238
Country          0
dtype: int64

In [96]:
df.dropna(inplace=True)

In [97]:
df.isna().sum().sum()

np.int64(0)

In [98]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
116637,546261,79302M,"ART LIGHTS,FUNK MONKEY",1,10/03/2011 15:01,2.95,17841.0,United Kingdom
488094,577794,82482,WOODEN PICTURE FRAME WHITE FINISH,18,21/11/2011 16:48,2.95,14030.0,United Kingdom
31362,538944,22904,CALENDAR PAPER CUT DESIGN,6,15/12/2010 11:21,2.95,13295.0,United Kingdom
138075,548188,21165,BEWARE OF THE CAT METAL SIGN,4,29/03/2011 15:12,1.69,13263.0,United Kingdom
309936,564147,21977,PACK OF 60 PINK PAISLEY CAKE CASES,24,23/08/2011 12:21,0.55,14004.0,United Kingdom

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 116637 to 408407
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    762 non-null    object
 1   StockCode    762 non-null    object
 2   Description  762 non-null    object
 3   Quantity     762 non-null    int64
 4   InvoiceDate  762 non-null    object
 5   UnitPrice    762 non-null    float64
 6   CustomerID   762 non-null    float64
 7   Country      762 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 53.6+ KB

In [100]:
df.describe()

         Quantity   UnitPrice    CustomerID
count  762.000000  762.000000    762.000000
mean    10.391076    2.886378  15296.847769
std     16.768559    3.584360   1723.192457
min    -25.000000    0.120000  12349.000000
25%      2.000000    1.250000  13997.250000
50%      6.000000    1.650000  15250.000000
75%     12.000000    3.750000  16778.500000
max    200.000000   40.000000  18272.000000

In [101]:
transactions = df.groupby('InvoiceNo')['Description'].apply(list).to_list()

In [102]:
itemsets, rules = apriori(transactions=transactions, min_support=0.001, min_confidence=0.3)

In [103]:
rules_date = []
for rule in rules:
    rules_date.append({'Rule': ', '.join(rule.lhs) + ' --> ' + ', '.join(rule.rhs), 'Lift' : rule.lift})

In [104]:
results = pd.DataFrame(rules_date).sort_values('Lift', ascending=False)

In [105]:
results.head()

                                                 Rule   Lift
0   LARGE CAKE TOWEL PINK SPOTS --> 200 RED + WHIT...  730.0
67  HEART CALCULATOR, MINI PLAYING CARDS FUN FAIR ...  730.0
77  HEART CALCULATOR --> KEY RING BASEBALL BOOT AS...  730.0
76  KEY RING BASEBALL BOOT ASSORTED  --> HEART CAL...  730.0
75  SET OF 3 WOODEN SLEIGH DECORATIONS --> HEART C...  730.0

In [106]:
results.to_csv('effiecient_df.csv', index=False)